creation_rules:
  - path_regex: secrets/.*
    pgp: '9A8F2B1C74E030CBBA768D034B8238C0BA575FAE'
  - path_regex: switch-engine-ceph-rclone-config.conf$
    pgp: '9A8F2B1C74E030CBBA768D034B8238C0BA575FAE'
  - path_regex: switch-ceph-s3.yaml$
    pgp: '9A8F2B1C74E030CBBA768D034B8238C0BA575FAE'
