# Not Yet Implemented
apiVersion: v1
kind: Namespace
metadata:
  name: csi-rclone-example-4
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-example
  namespace: csi-rclone-example-4
  labels:
    run: nginx-example
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: nginx-example
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-example
  namespace: csi-rclone-example-4
  labels:
    run: nginx-example
spec:
  containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx-example
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: data-rclone-example
  volumes:
    - name: data-rclone-example
      persistentVolumeClaim:
        claimName: csi-rclone-example-4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-rclone-example-4
  namespace: csi-rclone-example-4
  annotations:
    config-secret-name: rclone-secret-pvc
    config-secret-namespace: csi-rclone-example-4
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rclone-example-4
---
apiVersion: v1
kind: Secret
metadata:
  name: rclone-secret-pvc
  namespace: csi-rclone-example-4
type: Opaque
stringData:
    remote: ceph
    remotePath: csi-rclone-dev-test
    s3-provider: Ceph
    s3-access-key-id: "${S3_ACCESS_KEY_ID}"
    s3-secret-access-key: "${S3_SECRET_ACCESS_KEY}"
    s3-endpoint: "${S3_ENDPOINT}"
    s3-env-auth: "false"
