name: Publish chart
on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:
jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: azure/setup-helm@v3
        with:
          token: ${{secrets.GITHUB_TOKEN }}
      - name: install dependencies
        run: pip install chartpress
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Publish chart
        env:
          GITHUB_TOKEN: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
        run: |
          cd deploy
          git config --global user.email "arndt@menedev.de"
          git config --global user.name "Mene Bot"
          export TAG=$(echo ${GITHUB_REF} |cut -d/ -f3)
          helm dep update csi-rclone
          chartpress --tag $TAG --no-build --publish-chart
          
